Feature/3.2
flarebtw/TKI-142 pull request #17
Opened 2024-10-20 13:44 UTC by flarebtw

Скрипников Егор ТКИ-142 ЯП #16

2024-10-21 13:44 UTC, MarinaPaley requested changes

2024-10-21 13:44 UTC, MarinaPaley commented on 3.2/3.2.c
> +void checkQuantity(int quantity);
const

2024-10-21 13:44 UTC, MarinaPaley commented on 3.2/3.2.c
> +double nextElement(double previousElement, int k);
const

2024-10-21 13:44 UTC, MarinaPaley commented on 3.2/3.2.c
> +	if (quantity < 0)
У Вас последовательность с 1

2024-10-21 13:44 UTC, MarinaPaley commented on 3.2/3.2.c
> +		if (k > 1) {
Зачем?

2024-10-21 13:44 UTC, MarinaPaley commented on 3.2/3.2.c
> +double getSumNotLessThanE(const int n, const double e)
n не нужно

2024-10-23 09:07 UTC, BalakinaEP requested changes

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +	double Element = 1.0; // Первый член последовательности равен 1^4/1! = 1
`element`

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +	double sum = 0.0;
Потеряли первый член последовательности

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +	for (int k = 1; k <= n; ++k)
строго меньше n

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +		Element = nextElement(Element, k);
поменять местами

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +	return  previousElement * (pow(k, 4) / k);
знакопеременный ряд!

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +	while (Element >= e+DBL_EPSILON)
модуль элемента

2024-10-23 09:07 UTC, BalakinaEP commented on 3.2/3.2.c
> +	double Element = 1.0; // Первый член последовательности равен 1^4/1! = 1
`element`

2024-10-23 10:18 UTC, flarebtw commented on 3.2/3.2.c
> +	return  previousElement * (pow(k, 4) / k);
Так у меня же k в 4 степени, и факториал отрицательного числа не может быть определен, а также k принимает значения [1,n]

2024-10-23 11:31 UTC, BalakinaEP commented on 3.2/3.2.c
> +	return  previousElement * (pow(k, 4) / k);
А вы были на занятиях? Я явно сказала, что у всех знакопеременеый ряд. И в файле задание поменяли уже

2024-11-25 12:04 UTC, BalakinaEP requested changes

2024-11-25 12:04 UTC, BalakinaEP commented on 3.2/3.2.c
> +	const double e = input();
не проверяете, что e>0

2024-11-25 12:04 UTC, BalakinaEP commented on 3.2/3.2.c
> +	double element = 1.0; // Первый член последовательности равен 1^4/1! = 1
`double sum = element ;`

2024-12-02 13:40 UTC, BalakinaEP requested changes

2024-12-09 11:26 UTC, BalakinaEP requested changes

2024-12-09 11:26 UTC, BalakinaEP commented on 3.2/3.2.c
> +	double sum = element;
double sum = 0;

2024-12-09 11:26 UTC, BalakinaEP commented on 3.2/3.2.c
> +		sum += element;
поменять местами

2024-12-16 12:36 UTC, MarinaPaley approved these changes

2024-12-16 12:52 UTC, merged