Задание 4.1
flarebtw/TKI-142 pull request #21
Opened 2024-10-27 19:39 UTC by flarebtw

2024-10-29 17:05 UTC, BalakinaEP requested changes

2024-11-13 09:56 UTC, BalakinaEP requested changes

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +void printRandomArray(const size_t n, int* array);
интересно в чем же разница вывода массива? Какая Вам разница как он заполнен?

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +void printRandomArray(const size_t n, int* array);
массив в этой функции тоже не меняется

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +void printSourceArray(int* array, const size_t n);
Интересно, чем эта функция отличается от printRandomArray

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +void printIndicesDivisibleBy3(int* array, size_t n);
const

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +int hasAdjacentPairWithSum(int* array, size_t n, int targetSum);
const

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +    size_t n = input();
не проверили, что введенное значение положительно и присвоили его беззнаковой переменной. Получили огромное число

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +        printRandomArray(n, array);
Убрать

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +    size_t k = input();
То же самое с использованием `size_t`

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +    int* arrayInverted = (int*)malloc(n * sizeof(int));
не проверили, что память выделилась

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +    printf("\n");
У Вас как минимум две функции для печати массива

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +        array[i] = (rand() % 201) - 100;
Диапазон значений вводится пользователем с клавиатуры

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +    }
```
 for (size_t i = n - k; i < n; i++)
    {
        arrayInverted[i] = -array[i];
    }
```

А сразу так нельзя?

2024-11-13 09:56 UTC, BalakinaEP commented on 4.1/4.1.c
> +int hasAdjacentPairWithSum(int* array, size_t n, int targetSum)
Думаю, что эта функция должна быть void

2024-11-17 17:48 UTC, flarebtw commented on 4.1/4.1.c
> +    }
![image](https://github.com/user-attachments/assets/c8e51870-2da9-470c-84bc-9a85c5fc071a)
тогда элементы до задаются неверно

2024-11-22 12:38 UTC, BalakinaEP requested changes
не исправлены все замечания

2024-11-22 15:09 UTC, flarebtw commented on 4.1/4.1.c
> +    size_t n = input();
у меня две проверки, одна `checkPositive` которая проверяет вводимое значение, другая проверяет чтобы у n значение было неотрицательным
![image](https://github.com/user-attachments/assets/8de72873-4f70-4991-924f-635a9f098c64)

2024-11-22 15:09 UTC, flarebtw commented on 4.1/4.1.c
> +    size_t k = input();
тут тоже проверка `checkPositive`
![image](https://github.com/user-attachments/assets/7e723014-d35b-434c-8e3f-ac108668ee5d)

2024-11-25 12:14 UTC, BalakinaEP requested changes

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +void printArray(int* array, const size_t n);
const

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +void printIndicesDivisibleBy3(int* array, const size_t n);
const

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +void hasAdjacentPairWithSum(int* array, const size_t n, int targetSum);
const

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +    checkArray(arrayInverted);
Убрать

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +    invertLastKElements(arrayInverted, array, n, k);
invertLastKElements(arrayInverted, n, k);

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +void invertLastKElements(int* arrayInverted, int* array, const size_t n, const size_t k);
void invertLastKElements(int* arrayInverted, const size_t n, const size_t k);

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +    free(array);
В конце

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +    hasAdjacentPairWithSum(arrayInverted, n, targetSum);
В исходном

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +
free(arrayInverted);

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +void fillArrayRandom(int* array, const size_t n, const int a, const int b)
почему a и b

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +    int f = 0;
название

2024-11-25 12:14 UTC, BalakinaEP commented on 4.1/4.1.c
> +    int f = 0;
отдельная функция, которая просто ищет. Как только нашла, возвращает индекс, а если не нашла, например, -1.

2024-12-02 13:37 UTC, BalakinaEP requested changes

2024-12-09 11:23 UTC, BalakinaEP approved these changes

2024-12-09 11:23 UTC, BalakinaEP commented on 4.1/4.1.c
> +
checkArray(array);

2024-12-09 11:46 UTC, merged