Задание 4.2
flarebtw/TKI-142 pull request #25
Opened 2024-11-19 23:23 UTC by flarebtw

Скрипников Егор ТКИ-142

2024-11-22 13:42 UTC, BalakinaEP requested changes

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +void printArray(int* array, const size_t n);
Массив тоже константа

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +void checkArray(int* array);
Массив тоже константа

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +void createArrayAFromD(int* array, int* A, const size_t n);
Массив тоже константа

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    checkArray(clonnedArray);
Это не нужно

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    free(array);
Удаляете не тот массив

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    const int k = input();
не проверяете, что введенное значение Вас удовлетворяет

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    checkArray(A);
Это не нужно

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    int* A = getArray(n);
Почему А?

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    int* A = getArray(n);
Неверный размер

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    printArray(A, n);
А А размером cовсем не n

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +	checkArray(array);
Зачем?

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +    if (value < 0)
А нельзя здесь сразу проверить что значение >= 0? Зачем отдельная проверка в main?

2024-11-22 13:42 UTC, BalakinaEP commented on 4.2.c
> +void fillArrayRandom(int* array, const size_t n, const int a, const int b)
почему a и b ?

2024-11-22 19:06 UTC, flarebtw commented on 4.2.c
> +    int* A = getArray(n);
A потому что в условии массив А формируется

2024-11-25 14:06 UTC, MarinaPaley approved these changes

2024-11-26 08:58 UTC, merged